kind = "web"
previewPath = "/"
title = "PIL Printer"
version = "1.0.0"
id = "artifacts/pil-printer"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19613

[services.development]
run = "pnpm --filter @workspace/pil-printer run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/pil-printer", "run", "build" ]
publicDir = "artifacts/pil-printer/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19613"
BASE_PATH = "/"
